#Filebeat version 6.6.2

#-----------------------------Filebeat input --------------------------------

filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/oio/sds/OPENIO/rawx-0/rawx-0-httpd-access.log
    #- /var/log/oio/sds/OPENIO/*/*.log
  fields:
    name_log: rawx-0-httpd-access
- type: log
  enabled: true
  paths:
    - /var/log/oio/sds/OPENIO/*/*.access
  fields:
    name_log: access
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/meta0-0/meta0-0.log
#   fields:
#     name_log: meta-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/meta0-0/meta0-0.access
#   fields:
#     name_log: meta-0-access
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/conscience-0/conscience-0.log
#   fields:
#     name_log: conscience-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/oioproxy-0/oioproxy-0.access
#   fields:
#     name_log: oioproxy-0-access
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/oioproxy-0/oioproxy-0.log
#   fields:
#     name_log: oioproxy-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/conscienceagent-0/conscienceagent-0.log
#   fields:
#     name_log: conscienceagent-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO//ecd-0/ecd-0-httpd-access.log
#   fields:
#     name_log:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/ecd-0/ecd-0-httpd-errors.log
#   fields:
#     name_log:
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/ecd-0/oio-event-agent-0/oio-event-agent-0.log
#   fields:
#     name_log: oio-event-agent-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO//oio-blob-indexer-0/oio-blob-indexer-0.log
#   fields:
#     name_log: oio-blob-indexer-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/meta2-0/meta2-0.access
#   fields:
#     name_log: meta2-0.access
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/meta2-0/meta2-0.log
#   fields:
#     name_log: meta2-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/meta1-0/meta1-0.log
#   fields:
#     name_log: meta1-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/meta1-0/meta1-0.access
#   fields:
#     name_log: meta1-0-access
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/oioswift-0/oioswift-0.log
#   fields:
#     name_log: oioswift-0
# - type: log
#   enabled: true
#   paths:
#     - /var/log/oio/sds/OPENIO/redis-0/redis-0.log
#   fields:
#     name_log: redis-0
#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["192.168.1.43:5044"]
  #send data with the specific format with codecs
  #codec.format :
  #  string:  '%{[@timestamp]} %{[@message]}'

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-beats.crt"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
